FROM ubuntu:20.04

WORKDIR /src

RUN apt-get update && \
    apt-get upgrade -y

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -yq --no-install-recommends \
    git \
    cmake \
    build-essential \
    zlib1g-dev \
    libcgal-dev \
    nlohmann-json3-dev \
    libgtest-dev \
    libssl-dev

RUN git config --global http.sslverify false

RUN git clone https://github.com/arun11299/cpp-jwt.git

RUN cd cpp-jwt && mkdir build && cd build && \
    cmake .. && \
    cmake --build . -j

CMD ["tail", "-f","/dev/null"]
