name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - run: sudo apt-get update
      - run: sudo apt-get upgrade -y
      - run: export DEBIAN_FRONTEND=noninteractive
      - run: sudo apt-get install -y git cmake build-essential zlib1g-dev libcgal-dev nlohmann-json3-dev libgtest-dev libssl-dev
      - run: git config --global http.sslverify false
      - run: git clone https://github.com/arun11299/cpp-jwt.git
      - run: pwd && cd cpp-jwt && mkdir build && cd build && cmake .. && cmake --build . -j && ls -ltrha && ls -ltrha ../
      - run: git clone https://github.com/MalyuginRoman/testJWT
      - name: make test
        run: cp -rf testJWT cpp-jwt && cd cpp-jwt/build && make ..

      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
      - name: Check Test Coverage
        uses: threeal/gcovr-action@v1.1.0
      - name: Generate HTML Report
        uses: threeal/gcovr-action@v1.1.0
        with:
          html-out: coverage.html
          html-details: true
          html-title: My Project Test Coverage Report
          html-theme: github.green
      - name: Generate Coveralls Report
        uses: threeal/gcovr-action@v1.1.0
        with:
          coveralls-out: coveralls.json
