name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install libboost-all-dev -y
      - run: git config --global http.sslverify false
      - run: git clone https://github.com/arun11299/cpp-jwt.git
      - run: export DEBIAN_FRONTEND=noninteractive
      - run: sudo apt-get update;
             sudo apt-get install -yq --no-install-recommends \
             git \
             cmake \
             build-essential \
             zlib1g-dev \
             libcgal-dev \
             nlohmann-json3-dev \
             libgtest-dev \
             libssl-dev
      - run: cd cpp-jwt && mkdir build && cd build && \
             cmake .. && \
             cmake --build . -j
